### ISSUE TITLE
I am not getting results when I use reb files on macOS

### ISSUE THREAD

**Issue by danzek** [EricZimmerman/RECmd#45]
** RECmd version # **
2.0.0.0

**Describe the bug**
I get no results when using reb files on macOS. It says it found 0 key/value pairs. The exact same command and package on Windows finds 546 key/value pairs. 

They both find the same number of hives (on macOS and on Windows), and I know Registry parsing seems to be correct because I can use parameters like `sd`/`sk` to search content which works and returns expected results.

Command used:

    dotnet /Tools/RECmd/RECmd.dll -d '/Cases/12345/Systems/ABC1/hives' --bn '/Tools/RECmd/AllRegExecutablesFoundOrRun.reb' --csv /Cases/12345/Systems/ABC1/RECmdOutput/RegEXEsFoundOrRun --nl

I'm running dotnet v6.0.101 on macOS Big Sur 11.6.5.

**To Reproduce**
1. Run the above command on a folder containing Registry hives on macOS
2. Results on Windows shows 546 identified key/value pairs, on macOS it shows none

**Expected behavior**
It should find the same key/value pairs as when ran on the same data on Windows.

**Comment by EricZimmerman** [comment]
i dont have a mac to test this on. can you possibly get the source code and step thru it when using batch mode to see where it is not finding something? i dont know why it wouldnt work as it shouldnt be a path separator issue or anything like that. could it be the reb encoding?

what does --debug or trace show when its running?

**Comment by EricZimmerman** [comment]
or a CRLF vs LF issue?

**Comment by danzek** [comment]
The reb file is in ASCII encoding so that shouldn't be an issue (that was one of my first thoughts also). Line endings also appear fine.

Debug file:

[RECmd_debug.txt](https://github.com/EricZimmerman/RECmd/files/8817966/RECmd_debug.txt)

Trace file:

[trace.txt.zip](https://github.com/EricZimmerman/RECmd/files/8818022/trace.txt.zip)

Any weird path issues is more related to me altering the actual paths for privacy reasons.

**Comment by danzek** [comment]
It turns out I was running the .NET 4 v2.0.0.0 on Windows but .NET 6 v1.6.0.0 on macOS (but the tool output says 2.0.0.0, only the website says 1.6.0.0 when I download it).

Even so, I focused on a single key on Windows using the .NET 6 version and it found 143 key/value pairs in that specific key, whereas it found none on the same key in macOS. So the .NET version is not an issue.

Debug/trace logs for Windows:

[win.zip](https://github.com/EricZimmerman/RECmd/files/8818444/win.zip)

Debug/trace logs for macOS:

[mac.zip](https://github.com/EricZimmerman/RECmd/files/8818446/mac.zip)

I wonder if the same issue would occur on Linux also. I have not tested yet.

**Comment by EricZimmerman** [comment]
yea it looks like its based on how its finding the hive type.

if you can try linux at least we would know if its something with file path separator on windows vs the other 2 OSs

https://github.com/EricZimmerman/Registry/blob/9656033007a22de01f7d1abf52bb6ba9eeb2dbcc/Registry/RegistryBase.cs#L109

if you look at that hive in a hex editor, what does the path info look like:

https://github.com/EricZimmerman/Registry/blob/9656033007a22de01f7d1abf52bb6ba9eeb2dbcc/Registry/Other/RegistryHeader.cs#L54

windows:

[2022-06-01 19:18:11.8418955 DBG] Processing Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\System (HiveType match)
[2022-06-01 19:18:11.9696864 DBG] Processing Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\Module (HiveType match)

mac:
[2022-06-01 14:23:10.3842530 DBG] Skipping key Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\System because the current hive (Other) is not of the right type (Software)
[2022-06-01 14:23:10.3846360 DBG] Skipping key Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\Module because the current hive (Other) is not of the right type (Software)

**Comment by danzek** [comment]
I'm still doing testing including pon the same single hive in a Linux environment, but interestingly, `RECmd_Batch_MC.reb` does get some results, but not the same results as on Windows (less key-value pairs identified on macOS than on Windows).

However, `AllRegExecutablesFoundOrRun.reb` and `UserActivity.reb` do not find any key-value pairs on macOS (but do on Windows). All of them appear to have standard Unix (LF) line endings:

    > file *.reb
    AllRegExecutablesFoundOrRun.reb: ASCII text
    RECmd_Batch_MC.reb:              ASCII text
    UserActivity.reb:                ASCII text

I'll respond more specifically to the above also but sharing this for now.

**Comment by danzek** [comment]
Also no key/value pairs found on Linux for `AllRegExecutablesFoundOrRun.reb`.

Debug/trace logs for Linux:

[linux.zip](https://github.com/EricZimmerman/RECmd/files/8821139/linux.zip)

**Comment by danzek** [comment]
Offset 0x30 of the SOFTWARE hive with length of 64 bytes selected shows:

    0030h: 65 00 6D 00 52 00 6F 00 6F 00 74 00 5C 00 53 00  e.m.R.o.o.t.\.S. 
    0040h: 79 00 73 00 74 00 65 00 6D 00 33 00 32 00 5C 00  y.s.t.e.m.3.2.\. 
    0050h: 43 00 6F 00 6E 00 66 00 69 00 67 00 5C 00 53 00  C.o.n.f.i.g.\.S. 
    0060h: 4F 00 46 00 54 00 57 00 41 00 52 00 45 00 00 00  O.F.T.W.A.R.E... 

It appears to be a Unicode (UTF-16 LE) string as expected by https://github.com/EricZimmerman/Registry/blob/9656033007a22de01f7d1abf52bb6ba9eeb2dbcc/Registry/Other/RegistryHeader.cs#L54

**Comment by EricZimmerman** [comment]
this has to be it:

on linux:

[2022-06-02 00:47:41.1728431 DBG] Skipping key Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\System because the current hive (Other) is not of the right type (Software)
[2022-06-02 00:47:41.1731803 DBG] Skipping key Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\Module because the current hive (Other) is not of the right type (Software)

testing now

**Comment by EricZimmerman** [comment]
ok i know what it is. i use Path.getfilename for the embedded filename. on windows, it works, but mac/linux it doesnt since / vs \

fixing now then you can test again.

**Comment by danzek** [comment]
Unfortunately, the fix did not work on macOS. I also built it from source on my end to confirm (same result: no key/value pairs found). Updated debug and trace files:

[20220602_mac_debug_trace_logs.zip](https://github.com/EricZimmerman/RECmd/files/8828491/20220602_mac_debug_trace_logs.zip)

**Comment by EricZimmerman** [comment]
How about Linux? We only need the lines after the flushing stuff. Need to
see if it detected the filename correctly. I'll try on Linux on my side too
after building out a Linux VM.


At this point I would say focus on the registry test project and set some
breakpoints. That's where the issue is.

Will look more tomorrow

**Comment by EricZimmerman** [comment]
ok, i think i got it now. RECmd updated. please download and try again.

**Comment by danzek** [comment]
That fixed it! Same results on Mac and Windows now. Thanks!
